fun:
  chess_emojis:
    blunder: #<emoji_id>
    mistake: #<emoji_id>
    inaccuracy: #<emoji_id>
    excellent: #<emoji_id>
    best: #<emoji_id>
    brilliant: #<emoji_id>
  special_users:
    #<userid>:
    #- "<emoji>" OR
    #- ["<emoji1>", "<emoji2>", ...]
    #- ...

gameroom:
  default_hours: # MTWTFSS
    - '2:30PM - 11:00PM'
    - '2:30PM - 11:00PM'
    - '2:30PM - 11:00PM'
    - '2:30PM - 11:00PM'
    - '12:00PM - 11:00PM'
    - '12:00PM - 11:00PM'
    - '2:30PM - 11:00PM'
  adjusted_hours:
    2025-01-20: 'Closed (MLK Day)'
    2025-03-17: "2:30PM - 9:00PM (Finals Week)"
    2025-03-18: "2:30PM - 9:00PM (Finals Week)"
    2025-03-19: "2:30PM - 9:00PM (Finals Week)"
    2025-03-20: "2:30PM - 9:00PM (Finals Week)"
    2025-03-21: "12:00PM - 5:00PM (Finals Week)"
    2025-03-22: "Closed (Spring Break)"
    2025-03-23: "Closed (Spring Break)"
    2025-03-24: "Closed (Spring Break)"
    2025-03-25: "Closed (Spring Break)"
    2025-03-26: "Closed (Spring Break)"
    2025-03-27: "Closed (Spring Break)"
    2025-03-28: "Closed (Spring Break)"
    2025-03-29: "Closed (Spring Break)"
    2025-03-30: "Closed (Spring Break)"
    2025-03-31: "Closed (Spring Break)"
  games:
    ps4:
      - 'Call of Duty: Black Ops 4'
      - 'FIFA 23'
      - 'NBA 2K22'
      - 'Street Fighter V'
      - 'Guilty Gear Strive'
      - 'Guilty Gear Xrd Rev 2'
      - 'The King of Fighters XV'
      - 'Tekken 7'
      - 'Madden NFL 23'
      - 'Madden NFL 24'
      - 'Under Night In-Birth'
    ps5:
      - 'NBA 2K25'
      - 'NBA 2K22'
      - 'Madden NFL 25'
      - 'FC25'
      - 'Garfield Lasagna Party'
      - 'Hogwarts Legacy'
    n64:
      - 'F-Zero X'
      - 'Goldeneye 007'
      - 'Mario Kart 64'
      - 'Pokemon Stadium'
      - 'Super Smash Bros.'
    switch:
      - 'Super Smash Bros. Ultimate'
      - 'Mario Party Superstars'
      - 'New Super Mario Bros Deluxe'
      - 'Nintendo Switch Sports'
      - 'Mario Kart 8 Deluxe'
      - 'Snipperclips Plus'
      - 'Mario Strikers: Battle League'
    wii_u:
      - 'Splatoon'
      - 'Super Smash Bros. Brawl'
      - 'Super Smash Bros. Wii U'
      - 'Mario Kart Wii'
      - 'Lego Marvel Super Heroes'
    xbox:
      - 'Battlefield 1'
      - 'Mortal Kombat X'
      - 'Halo 5'
      - 'Madden 23'
      - 'Call of Duty: Black Ops 3'
      - 'Call of Duty: Modern Warfare II'

teams:

valorant:
  maps: # Release order
    - 'Bind'
    - 'Haven'
    - 'Split'
    - 'Ascent'
    - 'Icebox'
    - 'Breeze'
    - 'Fracture'
    - 'Pearl'
    - 'Lotus'
    - 'Sunset'
    - 'Abyss'
  maps_active: [1, 2, 3, 4, 6, 7, 8]
  agents: # Release order
    - 'Brimstone'
    - 'Viper'
    - 'Omen'
    - 'Cypher'
    - 'Sova'
    - 'Sage'
    - 'Phoenix'
    - 'Jett'
    - 'Raze'
    - 'Breach'
    - 'Reyna'
    - 'Killjoy'
    - 'Skye'
    - 'Yoru'
    - 'Astra'
    - 'KAY/O'
    - 'Chamber'
    - 'Neon'
    - 'Fade'
    - 'Harbor'
    - 'Gekko'
    - 'Deadlock'
    - 'Iso'
    - 'Clove'
    - 'Vyse'
    - 'Tejo'
    - "Waylay"
  agents_roles:
    controller: [0, 2, 14, 19, 23]
    duelist: [6, 7, 8, 10, 13, 17, 22, 26]
    initiator: [4, 9, 12, 15, 18, 20, 25]
    sentinel: [1, 3, 5, 11, 16, 21, 24] # Viper's here for better randomized teams

apis:
  ggleap: # link here

reservations:
  channel: #<channel_id>
  # who can invoke the reserve command
  roles:
    - #<role_id>
    - #<role_id>
    # - ...
